//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodItem
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public bool IsVegetarian { get; set; }
        public Nullable<int> Calories { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Description { get; set; }
        public Nullable<int> SpicinessLevel { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> Ratings { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
    
        public virtual FoodCategory FoodCategory { get; set; }
    }
}
